# TODO: add certbot for ssl
# Use the official Nginx image as a parent image
FROM nginx

# Remove default configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/
