version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - webnet

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    networks:
      - webnet
    depends_on:
      - app

networks:
  webnet:

